# Site settings
title: DESN-368 Web Design 1
email: ian@ianshea.me
description: > # this means to ignore newlines until "baseurl:"
  Course site for EWU Web Design 1 Winter 2016.
baseurl: "DESN-368/" # the subpath of your site, e.g. /blog/
url: "http://ianshea.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
